In [ ]:
"""
from google.colab import drive
drive.mount('/content/gdrive')
"""

In [10]:
#imports
#@title Import & seed
import time
import re
import os
import math
import numpy as np
from matplotlib import pyplot as plt
import requests
import collections
import pickle
import copy, random
import nltk as nl
nl.download('punkt')
from itertools import zip_longest

import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Input, Reshape, BatchNormalization, Dense, Dropout, concatenate,
    Embedding, LSTM, Dense, GRU, Bidirectional, Add
)
from tensorflow.keras.activations import elu, relu, softmax, sigmoid
from tensorflow.keras import regularizers
from tensorflow.keras.utils import to_categorical


#Variables
FILENAME = "divineComedyProf.txt"
CLEANFILENAME = "cleanComedyProf.txt"
INFERNO = "inferno_syllnew.txt"
PURGATORIO = "purgatorio_syllnew.txt"
PARADISO = "paradiso_syllnew.txt"
PARADISOCLEAN = "paradiso_clean.txt"


vocab_size = 1900
terces_per_batch = 8
terces_len = 200
batch_len = terces_per_batch * (terces_len + 1)
EPOCHS = 10


#Setup
print(tf.__version__)

#np.random.seed(1234)
!nvidia-smi

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
2.6.0
Wed Sep 22 20:16:56 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0    59W / 149W |   2216MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+------------------

In [2]:
#@title Setup wandb
!pip install wandb
!wandb login e6569c556c797b5bed38bc6cba40d24b68e8973d
import wandb
wandb.init(project="DeepComedy", name="bananito96")

     |████████████████████████████████| 1.7 MB 5.3 MB/s 
     |████████████████████████████████| 97 kB 5.5 MB/s 
     |████████████████████████████████| 139 kB 46.2 MB/s 
     |████████████████████████████████| 180 kB 47.1 MB/s 
     |████████████████████████████████| 63 kB 1.7 MB/s 
  Created wheel for subprocess32: filename=subprocess32-3.5.4-py3-none-any.whl size=6502 sha256=64c94bc3382e4380fd95323acdd782acdfbdabd817d3f7259843dc4e1566a857
  Stored in directory: /root/.cache/pip/wheels/50/ca/fa/8fca8d246e64f19488d07567547ddec8eb084e8c0d7a59226a
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8807 sha256=cb5ecadb402c359161c4a7bb33baed03e2105a3587d31438aeb735c3fe8a486d
  Stored in directory: /root/.cache/pip/wheels/3e/31/09/fa59cef12cdcfecc627b3d24273699f390e71828921b2cbba2
Successfully built subprocess32 pathtools
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


wandb: Currently logged in as: dropino (use `wandb login --relogin` to force relogin)


#Clean files


In [ ]:
"""
#count chars
char_list = []
with open(FILENAME) as file:
  while True:
    char = file.read(1)
    if not char:
      print("End of file")
      break
    char = char.lower()

    #add good char to char list
    if char not in char_list:
      char_list.append(char)

print(char_list)
"""

'\n#count chars\nchar_list = []\nwith open(FILENAME) as file:\n  while True:\n    char = file.read(1)\n    if not char:\n      print("End of file")\n      break\n    char = char.lower()\n\n    #add good char to char list\n    if char not in char_list:\n      char_list.append(char)\n\nprint(char_list)\n'

In [ ]:
"""
removable_chars = ['•', '—', '-', '(', ')', ',', '.', ':', ';', '“', '”', '«', '»', '"','0','1','2','3','4','5','6','7','8','9']
#‘ e ’ usate per racchiudere parti parlate in latino
#“ e ” racchiude il parlato sia in italiano che latino
#idem « e »


clean_char_list = []
removedCharsCounter = 0
fileOut = open(CLEANFILENAME, "a")

with open(FILENAME) as file:
  while True:
    char = file.read(1)
    if not char:
      print("End of file")
      break

    #transform upper case to lower case
    char = char.lower()

    #remove unwanted chars
    if char not in removable_chars:

      #add acceptable chars to char list
      if char not in clean_char_list:
        clean_char_list.append(char)
      
      #output in new file
      fileOut.write(char)
    else:
      removedCharsCounter += 1


print(char_list)
print(removedCharsCounter)
"""

'\nremovable_chars = [\'•\', \'—\', \'-\', \'(\', \')\', \',\', \'.\', \':\', \';\', \'“\', \'”\', \'«\', \'»\', \'"\',\'0\',\'1\',\'2\',\'3\',\'4\',\'5\',\'6\',\'7\',\'8\',\'9\']\n#‘ e ’ usate per racchiudere parti parlate in latino\n#“ e ” racchiude il parlato sia in italiano che latino\n#idem « e »\n\n\nclean_char_list = []\nremovedCharsCounter = 0\nfileOut = open(CLEANFILENAME, "a")\n\nwith open(FILENAME) as file:\n  while True:\n    char = file.read(1)\n    if not char:\n      print("End of file")\n      break\n\n    #transform upper case to lower case\n    char = char.lower()\n\n    #remove unwanted chars\n    if char not in removable_chars:\n\n      #add acceptable chars to char list\n      if char not in clean_char_list:\n        clean_char_list.append(char)\n      \n      #output in new file\n      fileOut.write(char)\n    else:\n      removedCharsCounter += 1\n\n\nprint(char_list)\nprint(removedCharsCounter)\n'

In [ ]:
"""
f = open(CLEANFILENAME, "r")
lines = f.readlines()

number_of_syllables = []
line_counter = 1

for line in lines:
  #excludes all empty lines and canto intros
  if '|' in line:
    syllables = line.count('|')
    number_of_syllables.append(syllables)
    if syllables != 11:
      print("line number {} with text {} has {} syllables".format(line_counter,line,syllables))
    line_counter += 1

Counter(number_of_syllables)
"""

'\nf = open(CLEANFILENAME, "r")\nlines = f.readlines()\n\nnumber_of_syllables = []\nline_counter = 1\n\nfor line in lines:\n  #excludes all empty lines and canto intros\n  if \'|\' in line:\n    syllables = line.count(\'|\')\n    number_of_syllables.append(syllables)\n    if syllables != 11:\n      print("line number {} with text {} has {} syllables".format(line_counter,line,syllables))\n    line_counter += 1\n\nCounter(number_of_syllables)\n'

# Tokenization

"""Once tokenized the dataset, a map of the syllables with the integer index is created. The final dimension
of the vocabulary is 1874 tokens but it is limited to 1800 to remove the tail of infrequent syllables.

We substituted every space between words with the special token < SEP > and inserted at the beginning
of each verse the token < GO >. To make all verses the same lengths, we used the special character
“< PAD >” to pad every terces to the length of 75 tokens. At the end of each verse we appended the
symbol “< EOV > “, while at the end of each sentence “< EOS >”."""

number_of_syllables = []
line_counter = 1
"""
space -> <SPA>
verst start -> <VST>
padding (up to 75) -> <PAD>
end of verse -> <EOV>
end of sentence -> <EOS>
"""


In [3]:
def get_hyp_lm_tercets(tercets):
    new_tercets = []
    for tercet in tercets:
        new_tercets.append([])
        for verse in tercet:
            new_tercets[-1].append([])
            for hyp_w in verse:
                new_tercets[-1][-1].extend(hyp_w)
                new_tercets[-1][-1].append('<SEP>')
            new_tercets[-1][-1] = new_tercets[-1][-1][:-1]

    return new_tercets



def get_dc_cantos(filename, encoding=None):
    # raw_data = read_words(filename=filename)
    cantos = []
    cantoCounter =  0
    cantos.append([])
    with open(filename, "r", encoding=encoding) as f:
        for line in f:
            sentence = line.strip()
            if 'canto' not in sentence and len(sentence) > 2:
                if len(sentence) > 2:
                    cantos[cantoCounter].append(sentence)
                    """
                    if len(cantos[cantoCounter]) == 3:
                      cantoCounter += 1
                      cantos.append([])
                    """
    return cantos


def create_tercets(cantos):
    tercets = []
    for i,canto in enumerate(cantos):
        for v,verse in enumerate(canto):
            if v%3 == 0:
                tercets.append([])

            tercets[-1].append(verse)
        tercets = tercets[:-1]  # removes the last malformed tercets (only 2 verses)

    return tercets

def pad_list(l, pad_token, max_l_size, keep_lasts=False, pad_right=True):
    """
    Adds a padding token to a list
    inputs:
    :param l: input list to pad.
    :param pad_token: value to add as padding.
    :param max_l_size: length of the new padded list to return,
    it truncates lists longer that 'max_l_size' without adding
    padding values.
    :param keep_lasts: If True, preserves the max_l_size last elements
    of a sequence (by keeping the same order).  E.g.:
    if keep_lasts is True and max_l_size=3 [1,2,3,4] becomes [2,3,4].


    :return: the list padded or truncated.
    """
    to_pad = []
    max_l = min(max_l_size, len(l))  # maximum len
    l_init = len(l) - max_l if len(l) > max_l and keep_lasts else 0  # initial position where to sample from the list
    l_end = len(l) if len(l) > max_l and keep_lasts else max_l
    for i in range(l_init, l_end):
        to_pad.append(l[i])

    # for j in range(len(l), max_l_size):
    #     to_pad.append(pad_token)
    pad_tokens = [pad_token] * (max_l_size-len(l))
    padded_l = to_pad + pad_tokens if pad_right else pad_tokens + to_pad

    return padded_l


def save_data(data, file):
    with open(file, 'wb') as output:
        pickle.dump(data, output, pickle.HIGHEST_PROTOCOL)

def load_data(file):
    with open(file, 'rb') as obj:
        return pickle.load(obj)

def print_and_write(file, s):
    print(s)
    file.write(s)


class Vocabulary(object):
    def __init__(self, vocab_size=None):
        self.dictionary = dict()
        self.rev_dictionary = dict()
        self.count = []
        self.special_tokens = []
        self.vocab_size = vocab_size

    def build_vocabulary_from_counts(self, count, special_tokens=[]):
        """
        Sets all the attributes of the Vocabulary object.
        :param count: a list of lists as follows: [['token', number_of_occurrences],...]
        :param special_tokens: a list of strings. E.g. ['<EOS>', '<PAD>',...]
        :return: None
        """

        dictionary = dict()
        for word, _ in count:
            dictionary[word] = len(dictionary)

        # adding eventual special tokens to the dictionary (e.g. <EOS>,<PAD> etc..)
        d = len(dictionary)
        for i, token in enumerate(special_tokens):
            dictionary[token] = d + i

        self.count = count
        self.dictionary = dictionary
        self.rev_dictionary = dict(zip(self.dictionary.values(), self.dictionary.keys()))
        self.special_tokens = special_tokens
        self.vocab_size = len(dictionary)

    def build_vocabulary_from_tokens(self, tokens, vocabulary_size=None, special_tokens=[]):
        """
        Given a list of tokens, it sets the Vocabulary object attributes by constructing
        a dictionary mapping each token to a unique id.
        :param tokens: a list of strings.
         E.g. ["the", "cat", "is", ... ".", "the", "house" ,"is" ...].
         NB: Here you should put all your token instances of the corpus.
        :param vocabulary_size: The number of elements of your vocabulary. If there are more
        than 'vocabulary_size' elements on tokens, it considers only the 'vocabulary_size'
        most frequent ones.
        :param special_tokens: Optional. A list of strings. Useful to add special tokens in vocabulary.
        If you don't have any, keep it empty.
        :return: None
        """

        vocabulary_size = vocabulary_size if vocabulary_size is not None else self.vocab_size
        vocabulary_size = vocabulary_size - (len(special_tokens) + 1) if vocabulary_size else None
        # counts occurrences of each token
        count = [['<UNK>', -1]]
        count.extend(collections.Counter(tokens).most_common(vocabulary_size))  # takes only the most frequent ones, if size is None takes them all
        self.build_vocabulary_from_counts(count, special_tokens)  # actually build the vocabulary
        self._set_unk_count(tokens)  # set the number of OOV instances

    @staticmethod
    def merge_vocabulary(vocab0, vocab1, vocabulary_size=-1):
        """
        Merge two Vocabulary objects into a new one.
        :param vocab0: first Vocabulary object
        :param vocab1: second Vocabulary object
        :param vocabulary_size: parameter to decide the merged vocabulary size.
        With default value -1, all the words of both vocabularies are preserved.
        When set to 0, the size of the vocabulary is set to the size of vocab0,
        when set to 1 it is kept the size of vocab1.
        :return: a new vocabulary
        """
        # get size of the new vocabulary
        vocab_size = vocab0.vocab_size + vocab1.vocab_size if vocabulary_size == -1 else vocabulary_size
        merged_special_tokens = list(set(vocab0.special_tokens) | set(vocab1.special_tokens))

        # merge the counts from the two vocabularies and then selects the most_common tokens
        merged_counts = collections.Counter(dict(vocab0.count)) + collections.Counter(dict(vocab1.count))
        merged_counts = merged_counts.most_common(vocab_size)
        count = [['<UNK>', -1]]
        count.extend(merged_counts)

        # create the new vocabulary
        merged_vocab = Vocabulary(vocab_size)
        merged_vocab.build_vocabulary_from_counts(count, merged_special_tokens)
        return merged_vocab

    @staticmethod
    def merge_vocabularies(vocab_list, vocab_size=None):
        """
        Join a list of vocabularies into a new one.
        :param vocab_list: a list of Vocabulary objects
        :param vocab_size: the maximum size of the merged vocabulary.
        :return: a vocabulary merging them all.
        """
        vocab_size = vocab_size if vocab_size else sum([v.vocab_size for v in vocab_list])
        merged_vocab = Vocabulary(vocab_size)
        for voc in vocab_list:
            merged_vocab = Vocabulary.merge_vocabulary(merged_vocab, voc, vocab_size)
        return merged_vocab

    def string2id(self, dataset):
        """
        Converts a dataset of strings into a dataset of ids according to the object dictionary.
        :param dataset: any string-based dataset with any nested lists.
        :return: a new dataset, with the same shape of dataset, where each string is mapped into its
        corresponding id associated in the dictionary (0 for unknown tokens).
        """

        def _recursive_call(items):
            new_items = []
            for item in items:
                if isinstance(item, str) or isinstance(item, int) or isinstance(item, float):
                    new_items.append(self.word2id(item))
                else:
                    new_items.append(_recursive_call(item))
            return new_items

        return _recursive_call(dataset)

    def id2string(self, dataset):
        """
        Converts a dataset of integer ids into a dataset of string according to the reverse dictionary.
        :param dataset: any int-based dataset with any nested lists. Allowed types are int, np.int32, np.int64.
        :return: a new dataset, with the same shape of dataset, where each token is mapped into its
        corresponding string associated in the reverse dictionary.
        """
        def _recursive_call(items):
            new_items = []
            for item in items:
                if isinstance(item, int) or isinstance(item, np.int) or isinstance(item, np.int32) or isinstance(item, np.int64):
                    new_items.append(self.id2word(item))
                else:
                    new_items.append(_recursive_call(item))
            return new_items

        return _recursive_call(dataset)

    def word2id(self, item):
        """
        Maps a string token to its corresponding id.
        :param item: a string.
        :return: If the token belongs to the vocabulary, it returns an integer id > 0, otherwise
        it returns the value associated to the unknown symbol, that is typically 0.
        """
        return self.dictionary[item] if item in self.dictionary else self.dictionary['<UNK>']

    def id2word(self, token_id):
        """
        Maps an integer token to its corresponding string.
        :param token_id: an integer.
        :return: If the id belongs to the vocabulary, it returns the string
        associated to it, otherwise it returns the string associated
        to the unknown symbol, that is '<UNK>'.
        """

        return self.rev_dictionary[token_id] if token_id in self.rev_dictionary else self.rev_dictionary[self.dictionary['<UNK>']]

    def get_unk_count(self):
        return self.count[0][1]

    def _set_unk_count(self, tokens):
        """
        Sets the number of OOV instances in the tokens provided
        :param tokens: a list of tokens
        :return: None
        """
        data = list()
        unk_count = 0
        for word in tokens:
            if word in self.dictionary:
                index = self.dictionary[word]
            else:
                index = 0  # dictionary['<UNK>']
                unk_count += 1
            data.append(index)
        self.count[0][1] = unk_count

    def add_element(self, name, is_special_token=False):
        if name not in self.dictionary:
            self.vocab_size += 1
            self.dictionary[name] = self.vocab_size
            self.rev_dictionary[self.vocab_size] = name

            if is_special_token:
                self.special_tokens = list(self.special_tokens)
                self.special_tokens.append(name)

            self.count.append([name, 1])

    def set_vocabulary(self, dictionary, rev_dictionary, special_tokens, vocab_size):
        self.dictionary = dictionary,
        self.rev_dictionary = rev_dictionary
        self.special_tokens = special_tokens
        self.vocab_size = vocab_size

    @staticmethod
    def load_vocabulary(filename):
        return load_data(filename)

    def save_vocabulary(self, filename):
        save_data(self, filename)

class SyLMDataset(object):
    def __init__(self, config, sy_vocab=None):
        self.config = config
        self.vocabulary = sy_vocab

        self.raw_train_x = []
        self.raw_val_x = []
        self.raw_test_x = []
        self.raw_x = []

        self.train_x, self.train_y = [], []
        self.val_x, self.val_y = [], []
        self.test_x, self.test_y = [], []
        self.x, self.y = [], []

    def initialize(self, sess):
        pass

    def load(self, sources):
        """
        Extract raw texts form sources and gather them all together.
        :param sources: a string or an iterable of strings containing the file(s)
        to process in order to build the dataset.
        :return: a list of raw strings.
        """
        return NotImplementedError

    def build(self, sources, split_size=0.8):
        """
        :param sources: a string or an iterable of strings containing the file(s)
        to process in order to build the dataset.
        :param split_size: the size to split the dataset, set >=1.0 to not split.
        """

        raw_x = self.load(sources)
        # raw_x = self.tokenize([self.preprocess(ex) for ex in raw_x])  # fixme
        # splitting data
        self.raw_x = raw_x
        if split_size < 1.0:
            self.raw_train_x, self.raw_test_x = self.split(self.raw_x, train_size=split_size)
            self.raw_train_x, self.raw_val_x = self.split(self.raw_train_x, train_size=split_size)
        else:
            self.raw_train_x = self.raw_x

        if self.vocabulary is None:
            # creates vocabulary
            tokens = [item for sublist in self.raw_train_x for item in sublist]  # get tokens
            special_tokens = ("<GO>", "<PAD>", "<SEP>", "<EOS>", "<EOV>")
            self._create_vocab(tokens, special_tokens=special_tokens)

        # creates x,y for train
        self.train_x = self._build_dataset(self.raw_train_x, insert_go=True, max_len=self.config.sentence_max_len, shuffle=False)
        self.train_y = self._build_dataset(self.raw_train_x, insert_go=True, max_len=self.config.sentence_max_len, shuffle=False)

        # creates x,y for validation
        self.val_x = self._build_dataset(self.raw_val_x, insert_go=True, max_len=self.config.sentence_max_len, shuffle=False)
        self.val_y = self._build_dataset(self.raw_val_x, insert_go=True, max_len=self.config.sentence_max_len, shuffle=False)

        # creates x,y for testing
        self.test_x = self._build_dataset(self.raw_test_x, insert_go=True, max_len=self.config.sentence_max_len, shuffle=False)
        self.test_y = self._build_dataset(self.raw_test_x, insert_go=True, max_len=self.config.sentence_max_len, shuffle=False)

    def _create_vocab(self, tokens, special_tokens=("<PAD>", "<GO>", "<SEP>", "<EOV>", "<EOS>")):
        """
        Create the vocabulary. Special tokens can be added to the tokens obtained from
        the corpus.
        :param tokens: a list of all the tokens in the corpus. Each token is a string.
        :param special_tokens: a list of strings.
        """
        print("creating_vocabulary") 

        vocab = Vocabulary(vocab_size=self.config.input_vocab_size)
        vocab.build_vocabulary_from_tokens(tokens, special_tokens=special_tokens)
        self.vocabulary = vocab

    @staticmethod
    def split(raw_data, train_size=0.8):
        size = math.floor(len(raw_data)*train_size)
        return raw_data[:size], raw_data[size:]

    @staticmethod
    def preprocess(txt):
        return txt

    @staticmethod
    def shuffle(x):
        return random.sample(x, len(x))

    @staticmethod
    def tokenize(txt):
        return txt

    def _build_dataset(self, raw_data, max_len=200, insert_go=True, keep_lasts=False, pad_right=True, shuffle=True):
        """
        Converts all the tokens in e1_raw_data by mapping each token with its corresponding
        value in the dictionary. In case of token not in the dictionary, they are assigned to
        a specific id. Each sequence is padded up to the seq_max_len setup in the config.

        :param raw_data: list of sequences, each sequence is a list of tokens (strings).
        :param max_len: max length of a sequence, crop longer and pad smaller ones.
        :param insert_go: True to insert <GO>, False otherwise.
        :param keep_lasts: True to truncate initial elements of a sequence.
        :param pad_right: pad to the right (default value True), otherwise pads to left.
        :param shuffle: Optional. If True data are shuffled.
        :return: A list of sequences where each token in each sequence is an int id.
        """
        dataset = []
        for sentence in raw_data:
            sentence_ids = [self.vocabulary.word2id("<GO>")] if insert_go else []
            sentence_ids.extend([self.vocabulary.word2id(w) for w in sentence])
            sentence_ids.append(self.vocabulary.word2id("<EOS>"))
            sentence_ids = pad_list(sentence_ids, self.vocabulary.word2id("<PAD>"), max_len, keep_lasts=keep_lasts, pad_right=pad_right)

            dataset.append(sentence_ids)

        if shuffle:
            return random.sample(dataset, len(dataset))
        else:
            return dataset

    def get_batches(self, batch_size=32, split_sel='train'):
        """
        Iterator over the training set. Useful method to run experiments.
        :param batch_size: size of the mini_batch
        :return: input and target.
        """
        if split_sel == 'train':
            x, y = self.train_x, self.train_y
        elif split_sel == 'val':
            x, y = self.val_x, self.val_y
        else:
            x, y = self.test_x, self.test_y
        
        i = 0 #random.randint(0, batch_size)
        batches = []
        eov = self.vocabulary.word2id("<EOV>")
        go = self.vocabulary.word2id("<GO>")
        # prepare batches
        while i < len(x):
            j = 0
            batch_x, batch_y = [], []
            while j < batch_size and i+j<len(x):
                for c in x[i+j]:
                  batch_x.append(c)
                batch_x.append(eov)
                for c in y[i+j]:
                  batch_y.append(c)
                batch_y.append(eov)
                j += 1
            i += batch_size
            batches.append((batch_x, batch_y))

        # supply
        i = 0
        while i < len(batches):
            yield batches[i][0], batches[i][1]
            i += 1

class DanteSyLMDataset(SyLMDataset):
    def __init__(self, config, sy_vocab=None):
        """
        Class to create a dataset from Dante Alighieri's Divine Comedy.
        :param config: a Config object
        :param sy_vocab: (optional) a Vocabulary object where tokens of the dictionary
        are syllables. If None, the vocabulary is create automatically from the source.
        """
        super().__init__(config, sy_vocab)

    def load(self, sources):
        """
        Load examples from dataset
        :param sources: data filepath.
        :return:
        """
        canti = get_dc_cantos(filename=sources)  # get raw data from files

        tercets = create_tercets(canti)
        #tercets = get_hyp_lm_tercets(tercets)
        x = []
        for tercet in tercets:
            x.append([])
            for verse in tercet:
                x[-1].extend(verse)
                x[-1].append("<EOV>")

        #x = self.shuffle(x)
        return x

def seq2str(seq):
    def output2string(batch, rev_vocabulary, special_tokens, end_of_tokens):
        to_print = ''
        for token in batch:
            if token in special_tokens:
                to_print += ' '
            elif end_of_tokens and token in end_of_tokens:
                to_print += '\n'
            elif token in rev_vocabulary:
                to_print += rev_vocabulary[token]
            else:
                to_print += '<UNK>'
        return to_print

    return output2string(seq, poetry_sy_lm_dataset.vocabulary.rev_dictionary,
      special_tokens=[poetry_sy_lm_dataset.vocabulary.word2id("<PAD>"), 
                      0, 
                      poetry_sy_lm_dataset.vocabulary.word2id("<SEP>"),
                      poetry_sy_lm_dataset.vocabulary.word2id("<GO>"), 
                      poetry_sy_lm_dataset.vocabulary.word2id("<EOS>")],
      end_of_tokens=[poetry_sy_lm_dataset.vocabulary.word2id("<EOV>")])

class cnfg:
  vocab_size = vocab_size
  input_vocab_size = vocab_size
  sentence_max_len = terces_len

config = cnfg()
poetry_sy_lm_dataset = DanteSyLMDataset(config, sy_vocab=None)

data_path = 'noSyllComedy.txt'  # dataset location, here just the name of the source file

poetry_sy_lm_dataset.build(data_path, split_size=0.99)  # actual creation of  vocabulary (if not provided) and dataset
print("Train size: " + str(len(poetry_sy_lm_dataset.train_y)))
print("Val size: " + str(len(poetry_sy_lm_dataset.val_y)))
print("Test size: " + str(len(poetry_sy_lm_dataset.test_y)))

eov = poetry_sy_lm_dataset.vocabulary.word2id("<EOV>")
pad = poetry_sy_lm_dataset.vocabulary.word2id("<PAD>")
go = poetry_sy_lm_dataset.vocabulary.word2id("<GO>")
eos = poetry_sy_lm_dataset.vocabulary.word2id("<EOS>")


batches = [b for b in poetry_sy_lm_dataset.get_batches(terces_per_batch)]
print(batches[0][0])
#print(batches[0][1])
print(len(batches[0][0]))
test_b = [b for b in poetry_sy_lm_dataset.get_batches(terces_per_batch, split_sel='test')]
#print(test_b[0][0])
#print(test_b[0][1])
print(len(test_b[0][0]))
val_b = [b for b in poetry_sy_lm_dataset.get_batches(terces_per_batch, split_sel='val')]
#print(val_b[0][0])
#print(val_b[0][1])
print(len(val_b[0][0]))
len(poetry_sy_lm_dataset.vocabulary.dictionary.items())

creating_vocabulary
Train size: 4636
Val size: 47
Test size: 48
[38, 6, 2, 8, 1, 15, 2, 24, 24, 5, 1, 12, 2, 8, 1, 11, 3, 15, 15, 4, 6, 1, 12, 4, 1, 6, 5, 10, 9, 7, 3, 1, 17, 4, 9, 3, 42, 15, 4, 1, 7, 4, 9, 7, 5, 17, 3, 4, 1, 16, 2, 7, 1, 14, 6, 3, 1, 10, 2, 8, 17, 3, 1, 5, 10, 11, 14, 7, 3, 42, 11, 20, 29, 1, 8, 3, 1, 12, 4, 7, 4, 9, 9, 3, 1, 17, 4, 3, 1, 2, 7, 3, 1, 10, 15, 3, 7, 7, 4, 9, 3, 42, 41, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 42, 38, 3, 20, 4, 1, 22, 14, 3, 6, 9, 5, 1, 3, 1, 12, 4, 7, 1, 22, 14, 3, 8, 1, 2, 7, 3, 1, 28, 1, 11, 5, 10, 3, 1, 12, 14, 7, 3, 42, 2, 10, 9, 3, 1, 10, 2, 8, 17, 3, 1, 10, 2, 8, 17, 3, 19, 19, 4, 3, 1, 2, 

42

In [4]:
poetry_sy_lm_dataset.vocabulary.dictionary

{' ': 1,
 '!': 32,
 '<EOS>': 41,
 '<EOV>': 42,
 '<GO>': 38,
 '<PAD>': 39,
 '<SEP>': 40,
 '<UNK>': 0,
 '?': 31,
 'a': 3,
 'b': 23,
 'c': 11,
 'd': 12,
 'e': 2,
 'f': 21,
 'g': 19,
 'h': 20,
 'i': 4,
 'j': 36,
 'l': 8,
 'm': 15,
 'n': 6,
 'o': 5,
 'p': 16,
 'q': 22,
 'r': 7,
 's': 10,
 't': 9,
 'u': 14,
 'v': 17,
 'x': 35,
 'y': 37,
 'z': 24,
 'à': 30,
 'è': 28,
 'é': 29,
 'ì': 25,
 'ò': 27,
 'ó': 33,
 'ù': 26,
 '‘': 34,
 '’': 18}

In [5]:
print(seq2str(batches[14][0]))
print(seq2str(batches[15][0]))
print(seq2str(batches[16][0]))


 vidi e conobbi l’ ombra di colui
che fece per viltade il gran rifiuto
incontanente intesi e certo fui
                                                                                                 
 che questa era la setta d’ i cattivi
a dio spiacenti e a’ nemici sui
questi sciaurati che mai non fur vivi
                                                                                            
 erano ignudi e stimolati molto
da mosconi e da vespe ch’ eran ivi
elle rigavan lor di sangue il volto
                                                                                                 
 che mischiato di lagrime a’ lor piedi
da fastidiosi vermi era ricolto
e poi ch’ a riguardar oltre mi diedi
                                                                                            
 vidi genti a la riva d’ un gran fiume
per ch’ io dissi maestro or mi concedi
ch’ i’ sappia quali sono e qual costume
                                                                              

# Model

In [6]:
wandb.config.num_layers = 4
wandb.config.d_model = 128
wandb.config.dff = 256
wandb.config.num_heads = 4
wandb.config.dropout = 0.1
wandb.config.learning_rate = 2e-4 

generate_at = [] #[10,20,30,40,50,60,70,80,90,100,110,120,130,140,150]

def get_angles(pos, i, d_model):
    angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
    return pos * angle_rates

def positional_encoding(position, d_model):
    angle_rads = get_angles(np.arange(position)[:, np.newaxis],
                            np.arange(d_model)[np.newaxis, :],
                            d_model)
    # apply sin to even indices in the array; 2i
    angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
    # apply cos to odd indices in the array; 2i+1
    angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
    pos_encoding = angle_rads[np.newaxis, ...]
    return tf.cast(pos_encoding, dtype=tf.float32)

def create_padding_mask(seq):   
    seq = tf.cast(tf.math.equal(seq, pad), tf.float32)
    # add extra dimensions to add the padding
    # to the attention logits.
    return seq[:, tf.newaxis, tf.newaxis, :]  # (batch_size, 1, 1, seq_len)

def create_look_ahead_mask(size):
    mask = 1 - tf.linalg.band_part(tf.ones((size, size)), -1, 0)
    return mask  # (seq_len, seq_len)

def scaled_dot_product_attention(q, k, v, mask):
    """Calculate the attention weights.
    q, k, v must have matching leading dimensions.
    k, v must have matching penultimate dimension, i.e.: seq_len_k = seq_len_v.
    The mask has different shapes depending on its type(padding or look ahead) 
    but it must be broadcastable for addition.
    
    Args:
        q: query shape == (..., seq_len_q, depth)
        k: key shape == (..., seq_len_k, depth)
        v: value shape == (..., seq_len_v, depth_v)
        mask: Float tensor with shape broadcastable 
            to (..., seq_len_q, seq_len_k). Defaults to None.
        
    Returns:
        output, attention_weights
    """
    matmul_qk = tf.matmul(q, k, transpose_b=True)  # (..., seq_len_q, seq_len_k)
    # scale matmul_qk
    dk = tf.cast(tf.shape(k)[-1], tf.float32)
    scaled_attention_logits = matmul_qk / tf.math.sqrt(dk)
    # add the mask to the scaled tensor.
    if mask is not None:
        scaled_attention_logits += (mask * -1e9)  
    # softmax is normalized on the last axis (seq_len_k) so that the scores
    # add up to 1.
    attention_weights = tf.nn.softmax(scaled_attention_logits, axis=-1)  # (..., seq_len_q, seq_len_k)
    output = tf.matmul(attention_weights, v)  # (..., seq_len_q, depth_v)
    return output, attention_weights

def point_wise_feed_forward_network(d_model, dff):
    return tf.keras.Sequential([
        tf.keras.layers.Dense(dff, activation='relu'),  # (batch_size, seq_len, dff)
        tf.keras.layers.Dense(d_model)  # (batch_size, seq_len, d_model)
    ])


class MultiHeadAttention(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads):
        super(MultiHeadAttention, self).__init__()
        self.num_heads = num_heads
        self.d_model = d_model
        assert d_model % self.num_heads == 0
        self.depth = d_model // self.num_heads
        self.wq = tf.keras.layers.Dense(d_model)
        self.wk = tf.keras.layers.Dense(d_model)
        self.wv = tf.keras.layers.Dense(d_model)
        self.dense = tf.keras.layers.Dense(d_model)
            
    def split_heads(self, x, batch_size):
        """Split the last dimension into (num_heads, depth).
        Transpose the result such that the shape is (batch_size, num_heads, seq_len, depth)
        """
        x = tf.reshape(x, (batch_size, -1, self.num_heads, self.depth))
        return tf.transpose(x, perm=[0, 2, 1, 3])
        
    def call(self, v, k, q, mask):
        batch_size = tf.shape(q)[0]
        
        q = self.wq(q)  # (batch_size, seq_len, d_model)
        k = self.wk(k)  # (batch_size, seq_len, d_model)
        v = self.wv(v)  # (batch_size, seq_len, d_model)
        
        q = self.split_heads(q, batch_size)  # (batch_size, num_heads, seq_len_q, depth)
        k = self.split_heads(k, batch_size)  # (batch_size, num_heads, seq_len_k, depth)
        v = self.split_heads(v, batch_size)  # (batch_size, num_heads, seq_len_v, depth)
        
        # scaled_attention.shape == (batch_size, num_heads, seq_len_q, depth)
        # attention_weights.shape == (batch_size, num_heads, seq_len_q, seq_len_k)
        scaled_attention, attention_weights = scaled_dot_product_attention(q, k, v, mask)
        scaled_attention = tf.transpose(scaled_attention, perm=[0, 2, 1, 3])  # (batch_size, seq_len_q, num_heads, depth)
        concat_attention = tf.reshape(scaled_attention, 
                                    (batch_size, -1, self.d_model))  # (batch_size, seq_len_q, d_model)
        output = self.dense(concat_attention)  # (batch_size, seq_len_q, d_model)
        return output, attention_weights

class EncoderLayer(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads, dff, rate=0.1):
        super(EncoderLayer, self).__init__()

        self.mha = MultiHeadAttention(d_model, num_heads)
        self.ffn = point_wise_feed_forward_network(d_model, dff)

        self.layernorm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        
        self.dropout1 = tf.keras.layers.Dropout(rate)
        self.dropout2 = tf.keras.layers.Dropout(rate)
        
    def __call__(self, x, training, mask):
        attn_output, _ = self.mha(x, x, x, mask)  # (batch_size, input_seq_len, d_model)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(x + attn_output)  # (batch_size, input_seq_len, d_model)

        ffn_output = self.ffn(out1)  # (batch_size, input_seq_len, d_model)
        ffn_output = self.dropout2(ffn_output, training=training)
        out2 = self.layernorm2(out1 + ffn_output)  # (batch_size, input_seq_len, d_model)
        
        return out2

class DecoderLayer(tf.keras.layers.Layer):
    def __init__(self, d_model, num_heads, dff, rate=0.1):
        super(DecoderLayer, self).__init__()

        self.mha1 = MultiHeadAttention(d_model, num_heads)
        self.mha2 = MultiHeadAttention(d_model, num_heads)

        self.ffn = point_wise_feed_forward_network(d_model, dff)
    
        self.layernorm1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm3 = tf.keras.layers.LayerNormalization(epsilon=1e-6)
        
        self.dropout1 = tf.keras.layers.Dropout(rate)
        self.dropout2 = tf.keras.layers.Dropout(rate)
        self.dropout3 = tf.keras.layers.Dropout(rate)
        
        
    def __call__(self, x, enc_output, training, 
            look_ahead_mask, padding_mask):
        # enc_output.shape == (batch_size, input_seq_len, d_model)

        attn1, attn_weights_block1 = self.mha1(x, x, x, look_ahead_mask)  # (batch_size, target_seq_len, d_model)
        attn1 = self.dropout1(attn1, training=training)
        out1 = self.layernorm1(attn1 + x)
        
        attn2, attn_weights_block2 = self.mha2(
            enc_output, enc_output, out1, padding_mask)  # (batch_size, target_seq_len, d_model)
        attn2 = self.dropout2(attn2, training=training)
        out2 = self.layernorm2(attn2 + out1)  # (batch_size, target_seq_len, d_model)
        
        ffn_output = self.ffn(out2)  # (batch_size, input_seq_len, d_model)
        ffn_output = self.dropout3(ffn_output, training=training)
        out3 = self.layernorm3(ffn_output + out2)  # (batch_size, target_seq_len, d_model)
        
        return out3, attn_weights_block1, attn_weights_block2

class Encoder(tf.keras.layers.Layer):
    def __init__(self, num_layers, d_model, num_heads, dff, input_vocab_size,
                maximum_position_encoding, rate=0.1):
        super(Encoder, self).__init__()
        self.d_model = d_model
        self.num_layers = num_layers
        self.embedding = tf.keras.layers.Embedding(input_vocab_size, d_model)
        self.pos_encoding = positional_encoding(maximum_position_encoding, 
                                                self.d_model)
        self.enc_layers = [EncoderLayer(d_model, num_heads, dff, rate) 
                        for _ in range(num_layers)]
        self.dropout = tf.keras.layers.Dropout(rate)
            
    def __call__(self, x, training, mask):
        seq_len = tf.shape(x)[1]
        # adding embedding and position encoding.
        x = self.embedding(x)  # (batch_size, input_seq_len, d_model)
        x *= tf.math.sqrt(tf.cast(self.d_model, tf.float32))
        x += self.pos_encoding[:, :seq_len, :]
        x = self.dropout(x, training=training)
        for i in range(self.num_layers):
            x = self.enc_layers[i](x, training, mask)
        return x  # (batch_size, input_seq_len, d_model)

class Decoder(tf.keras.layers.Layer):
    def __init__(self, num_layers, d_model, num_heads, dff, target_vocab_size,
                maximum_position_encoding, rate=0.1):
        super(Decoder, self).__init__()
        self.d_model = d_model
        self.num_layers = num_layers
        self.embedding = tf.keras.layers.Embedding(target_vocab_size, d_model)
        self.pos_encoding = positional_encoding(maximum_position_encoding, d_model)
        self.dec_layers = [DecoderLayer(d_model, num_heads, dff, rate) 
                        for _ in range(num_layers)]
        self.dropout = tf.keras.layers.Dropout(rate)
        
    def __call__(self, x, enc_output, training, look_ahead_mask, padding_mask):
        seq_len = tf.shape(x)[1]
        attention_weights = {}
        x = self.embedding(x)  # (batch_size, target_seq_len, d_model)
        x *= tf.math.sqrt(tf.cast(self.d_model, tf.float32))
        x += self.pos_encoding[:, :seq_len, :]
        x = self.dropout(x, training=training)
        for i in range(self.num_layers):
            x, block1, block2 = self.dec_layers[i](x, enc_output, training,
                                                look_ahead_mask, padding_mask)
            attention_weights['decoder_layer{}_block1'.format(i+1)] = block1
            attention_weights['decoder_layer{}_block2'.format(i+1)] = block2
        
        # x.shape == (batch_size, target_seq_len, d_model)
        return x, attention_weights

class Transformer(tf.keras.Model):
    def __init__(self, num_layers, d_model, num_heads, dff, input_vocab_size, 
                target_vocab_size, pe_input, pe_target, rate=0.1):
        super(Transformer, self).__init__()

        self.encoder = Encoder(num_layers, d_model, num_heads, dff, 
                            input_vocab_size, pe_input, rate)

        self.decoder = Decoder(num_layers, d_model, num_heads, dff, 
                            target_vocab_size, pe_target, rate)

        self.final_layer = tf.keras.layers.Dense(target_vocab_size)
        
    def __call__(self, inp, tar, training, enc_padding_mask, 
            look_ahead_mask, dec_padding_mask):

        enc_output = self.encoder(inp, training, enc_padding_mask)  # (batch_size, inp_seq_len, d_model)
        
        # dec_output.shape == (batch_size, tar_seq_len, d_model)
        dec_output, attention_weights = self.decoder(
            tar, enc_output, training, look_ahead_mask, dec_padding_mask)
        
        final_output = self.final_layer(dec_output)  # (batch_size, tar_seq_len, target_vocab_size)
        
        return final_output, attention_weights

optimizer = tf.keras.optimizers.Adam(wandb.config.learning_rate, beta_1=0.9, beta_2=0.98, 
                                     epsilon=1e-9)

loss_object = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True, reduction='none')

def loss_function(real, pred):
    mask = tf.math.logical_not(tf.math.equal(real, 0))
    loss_ = loss_object(real, pred)
    mask = tf.cast(mask, dtype=loss_.dtype)
    loss_ *= mask
    return tf.reduce_sum(loss_)/tf.reduce_sum(mask)

train_loss = tf.keras.metrics.Mean(name='train_loss')
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
    name='train_accuracy')

val_loss = tf.keras.metrics.Mean(name='train_loss')
val_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
    name='train_accuracy')

input_vocab_size = vocab_size
target_vocab_size = vocab_size
max_len = batch_len

transformer = Transformer(wandb.config.num_layers, wandb.config.d_model, 
                          wandb.config.num_heads, wandb.config.dff,
                          input_vocab_size, target_vocab_size, 
                          pe_input=max_len, 
                          pe_target=max_len,
                          rate=wandb.config.dropout)
def create_masks(inp, tar):
    # Encoder padding mask
    enc_padding_mask = create_padding_mask(inp)
    
    # Used in the 2nd attention block in the decoder.
    # This padding mask is used to mask the encoder outputs.
    dec_padding_mask = create_padding_mask(inp)
    
    # Used in the 1st attention block in the decoder.
    # It is used to pad and mask future tokens in the input received by 
    # the decoder.
    look_ahead_mask = create_look_ahead_mask(tf.shape(tar)[1])
    dec_target_padding_mask = create_padding_mask(tar)
    combined_mask = tf.maximum(dec_target_padding_mask, look_ahead_mask)
    
    return enc_padding_mask, combined_mask, dec_padding_mask

checkpoint_path = "./checkpoints/train"

ckpt = tf.train.Checkpoint(transformer=transformer,
                           optimizer=optimizer)
ckpt_manager = tf.train.CheckpointManager(ckpt, checkpoint_path, max_to_keep=5)
# if a checkpoint exists, restore the latest checkpoint.
if ckpt_manager.latest_checkpoint:
    ckpt.restore(ckpt_manager.latest_checkpoint)
    print ('Latest checkpoint restored!!')

@tf.function()
def train_step(inp, tar):
    tar_inp = tar[:, :-1]
    tar_real = tar[:, 1:]
    enc_padding_mask, combined_mask, dec_padding_mask = create_masks(inp, tar_inp)
    
    with tf.GradientTape() as tape:
        predictions, _ = transformer(inp, tar_inp, 
                                    True, 
                                    enc_padding_mask, 
                                    combined_mask, 
                                    dec_padding_mask)
        loss = loss_function(tar_real, predictions)
        gradients = tape.gradient(loss, transformer.trainable_variables)    
        optimizer.apply_gradients(zip(gradients, transformer.trainable_variables))
    
    train_loss(loss)
    train_accuracy(tar_real, predictions)

@tf.function()
def val_step(inp, tar):
    tar_inp = tar[:, :-1]
    tar_real = tar[:, 1:]
    enc_padding_mask, combined_mask, dec_padding_mask = create_masks(inp, tar_inp)
    
    predictions, _ = transformer(inp, tar_inp, 
                                False, 
                                enc_padding_mask, 
                                combined_mask, 
                                dec_padding_mask)
    loss = loss_function(tar_real, predictions)
    
    val_loss(loss)
    val_accuracy(tar_real, predictions)

In [7]:
#@title Generation
def generate(index=0, k=1, t=1):

    def evaluate_greedy(inp_sentence, decoder_input):
        inp_sentence = inp_sentence
        encoder_input = tf.expand_dims(inp_sentence, 0)
        
        output = tf.expand_dims(decoder_input, 0)

        terces = 0
        for i in range(batch_len):
            enc_padding_mask, combined_mask, dec_padding_mask = create_masks(
                encoder_input, output)
        
            # predictions.shape == (batch_size, seq_len, vocab_size)
            predictions, attention_weights = transformer(encoder_input, 
                                                        output,
                                                        False,
                                                        enc_padding_mask,
                                                        combined_mask,
                                                        dec_padding_mask)
            
            # select the last word from the seq_len dimension
            predictions = predictions[: ,-1:, :]  # (batch_size, 1, vocab_size)

            predicted_id = tf.cast(tf.argmax(predictions, axis=-1), tf.int32)

            # return the result if the predicted_id is equal to the end token
            if predicted_id == eos:
                terces += 1
                if terces == terces_per_batch-1:
                    return tf.squeeze(output, axis=0), attention_weights
            # concatentate the predicted_id to the output which is given to the decoder
            # as its input.
            output = tf.concat([output, predicted_id], axis=-1)

        return tf.squeeze(output, axis=0), attention_weights


    def evaluate_topk(inp_sentence, decoder_input, k=5, temperature=0.5):
        inp_sentence = inp_sentence
        encoder_input = tf.expand_dims(inp_sentence, 0)
        
        output = tf.expand_dims(decoder_input, 0)

        def scale(tensor):
            tensor = tf.math.divide(
                tf.subtract(
                    tensor, 
                    tf.reduce_min(tensor)
                ), 
                tf.subtract(
                    tf.reduce_max(tensor), 
                    tf.reduce_min(tensor))
                )
            return tensor

        terces = 0
        for i in range(batch_len):
            enc_padding_mask, combined_mask, dec_padding_mask = create_masks(
                encoder_input, output)
        
            # predictions.shape == (batch_size, seq_len, vocab_size)
            predictions, attention_weights = transformer(encoder_input, 
                                                        output,
                                                        False,
                                                        enc_padding_mask,
                                                        combined_mask,
                                                        dec_padding_mask)
            # select the last word from the seq_len dimension
            predictions = predictions[: ,-1:, :]  # (batch_size, 1, vocab_size)
            predictions, indices = tf.math.top_k(predictions,k=k)
            predictions /= temperature
            #predictions = scale(predictions)
            predictions = np.squeeze(predictions, axis=0)
            indices = np.squeeze(indices, axis=0)
            indices = np.squeeze(indices, axis=0)
            predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
            predicted_id = indices[predicted_id]

            # return the result if the predicted_id is equal to the end token
            if predicted_id == eos:
                terces += 1
                if terces == terces_per_batch-1:
                    return tf.squeeze(output, axis=0), attention_weights
            # concatentate the predicted_id to the output which is given to the decoder
            # as its input.
            predicted_id = tf.expand_dims(predicted_id, 0)
            predicted_id = tf.expand_dims(predicted_id, 0)
            output = tf.concat([output, predicted_id], axis=-1)

        return tf.squeeze(output, axis=0), attention_weights

    out_list = test_b[index][0]
    offset = terces_len # a tercet
    txt_gen = seq2str(out_list[-offset:])

    print("params: k={}, t={}".format(k,t))
    for i in range(32//(terces_per_batch-1)): # 30 terces = cantica
        out, att_w = evaluate_topk([pad], out_list[-offset:], k, t)
        out_list = out.numpy().tolist()
        out_str = seq2str(out_list[offset:])
        txt_gen += out_str

    print(txt_gen)
    wandb.log({"generated":
            wandb.Html("k="+str(k)+" t="+str(t)+
                       "<pre>"+txt_gen+"</pre>", inject=False)})

# Train Loop

In [12]:
#@title Train loop

for epoch in range(EPOCHS):
    start_time = time.time()
    random.shuffle(batches)
    start = time.time()
    
    train_loss.reset_states()
    train_accuracy.reset_states()
    
    for (batch, (inp, tar)) in enumerate(batches):
        if (len(inp) != batch_len or len(tar) != batch_len):
            print("discarded batch", batch)
            continue
        train_step(np.expand_dims(inp, axis=0), np.expand_dims(tar, axis=0))
        
        if batch % 50 == 0:
            print ('Epoch {} Batch {} Loss {:.4f} Accuracy {:.4f}'.format(
                epoch + 1, batch, train_loss.result(), train_accuracy.result()))
        
    if (epoch + 1) % 5 == 0:
        ckpt_save_path = ckpt_manager.save()
        print ('Saving checkpoint for epoch {} at {}'.format(epoch+1, ckpt_save_path))

    print ('Epoch {} Loss {:.4f} Accuracy {:.4f}'.format(epoch + 1, train_loss.result(), train_accuracy.result()))
    print ('Time taken for 1 epoch: {} secs\n'.format(time.time() - start))

    wandb.log({
        'train_loss': train_loss.result(),
        'train_accuracy': train_accuracy.result()
    }, step=epoch+1)

    # validation
    if epoch % 5 == 0:
        loss_l, acc_l = [], []
        for (batch, (inp, tar)) in enumerate(val_b):
            val_loss.reset_states()
            val_accuracy.reset_states()
            
            if (len(inp) != batch_len or len(tar) != batch_len):
                print("discarded batch", batch)
                continue

            val_step(np.expand_dims(inp, axis=0), np.expand_dims(tar, axis=0))

            loss_l.append(val_loss.result())
            acc_l.append(val_accuracy.result())

        loss_mean = sum(loss_l)/len(loss_l)
        acc_mean = sum(acc_l)/len(acc_l)
        print('Epoch {} VALIDATION: Loss {:.4f} Accuracy {:.4f}\n'.format(epoch + 1, loss_mean, acc_mean))

        wandb.log({
            'val_loss': loss_mean,
            'val_accuracy': acc_mean
        }, step=epoch+1)

    # generation
    if epoch in generate_at:
        generate(1)
    
    print("epoch lasted: {}".format(time.time()-start_time))

Epoch 1 Batch 0 Loss 1.1814 Accuracy 0.6192
Epoch 1 Batch 50 Loss 1.1709 Accuracy 0.6263
Epoch 1 Batch 100 Loss 1.1699 Accuracy 0.6265
Epoch 1 Batch 150 Loss 1.1679 Accuracy 0.6270
Epoch 1 Batch 200 Loss 1.1667 Accuracy 0.6275
Epoch 1 Batch 250 Loss 1.1649 Accuracy 0.6279
Epoch 1 Batch 300 Loss 1.1645 Accuracy 0.6276
Epoch 1 Batch 350 Loss 1.1637 Accuracy 0.6277
Epoch 1 Batch 400 Loss 1.1632 Accuracy 0.6280
discarded batch 445
Epoch 1 Batch 450 Loss 1.1621 Accuracy 0.6284
Epoch 1 Batch 500 Loss 1.1619 Accuracy 0.6285
Epoch 1 Batch 550 Loss 1.1611 Accuracy 0.6288


wandb: WARNING Step must only increase in log calls.  Step 1 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.1609067>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6288625>}.


Epoch 1 Loss 1.1609 Accuracy 0.6289
Time taken for 1 epoch: 111.7916145324707 secs



wandb: WARNING Step must only increase in log calls.  Step 1 < 11; dropping {'val_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.1032584>, 'val_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6423149>}.


discarded batch 5
Epoch 1 VALIDATION: Loss 1.1033 Accuracy 0.6423

epoch lasted: 112.17712211608887
Epoch 2 Batch 0 Loss 1.1436 Accuracy 0.6385
discarded batch 34
Epoch 2 Batch 50 Loss 1.1556 Accuracy 0.6331
Epoch 2 Batch 100 Loss 1.1535 Accuracy 0.6329
Epoch 2 Batch 150 Loss 1.1516 Accuracy 0.6328
Epoch 2 Batch 200 Loss 1.1514 Accuracy 0.6320
Epoch 2 Batch 250 Loss 1.1500 Accuracy 0.6325
Epoch 2 Batch 300 Loss 1.1492 Accuracy 0.6324
Epoch 2 Batch 350 Loss 1.1492 Accuracy 0.6325
Epoch 2 Batch 400 Loss 1.1493 Accuracy 0.6326
Epoch 2 Batch 450 Loss 1.1494 Accuracy 0.6326
Epoch 2 Batch 500 Loss 1.1484 Accuracy 0.6329
Epoch 2 Batch 550 Loss 1.1470 Accuracy 0.6335


wandb: WARNING Step must only increase in log calls.  Step 2 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.1463903>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6336494>}.


Epoch 2 Loss 1.1464 Accuracy 0.6336
Time taken for 1 epoch: 111.76030445098877 secs

epoch lasted: 111.7658064365387
Epoch 3 Batch 0 Loss 1.1411 Accuracy 0.6322
Epoch 3 Batch 50 Loss 1.1301 Accuracy 0.6379
Epoch 3 Batch 100 Loss 1.1335 Accuracy 0.6375
Epoch 3 Batch 150 Loss 1.1348 Accuracy 0.6370
Epoch 3 Batch 200 Loss 1.1336 Accuracy 0.6372
Epoch 3 Batch 250 Loss 1.1334 Accuracy 0.6374
Epoch 3 Batch 300 Loss 1.1324 Accuracy 0.6377
Epoch 3 Batch 350 Loss 1.1315 Accuracy 0.6380
Epoch 3 Batch 400 Loss 1.1303 Accuracy 0.6385
discarded batch 440
Epoch 3 Batch 450 Loss 1.1302 Accuracy 0.6386
Epoch 3 Batch 500 Loss 1.1299 Accuracy 0.6386
Epoch 3 Batch 550 Loss 1.1295 Accuracy 0.6389


wandb: WARNING Step must only increase in log calls.  Step 3 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.129102>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6391403>}.


Epoch 3 Loss 1.1291 Accuracy 0.6391
Time taken for 1 epoch: 111.64289450645447 secs

epoch lasted: 111.6483211517334
Epoch 4 Batch 0 Loss 1.1289 Accuracy 0.6490
Epoch 4 Batch 50 Loss 1.1125 Accuracy 0.6442
Epoch 4 Batch 100 Loss 1.1127 Accuracy 0.6436
Epoch 4 Batch 150 Loss 1.1127 Accuracy 0.6437
discarded batch 161
Epoch 4 Batch 200 Loss 1.1153 Accuracy 0.6428
Epoch 4 Batch 250 Loss 1.1145 Accuracy 0.6434
Epoch 4 Batch 300 Loss 1.1138 Accuracy 0.6437
Epoch 4 Batch 350 Loss 1.1144 Accuracy 0.6432
Epoch 4 Batch 400 Loss 1.1139 Accuracy 0.6435
Epoch 4 Batch 450 Loss 1.1132 Accuracy 0.6436
Epoch 4 Batch 500 Loss 1.1129 Accuracy 0.6437
Epoch 4 Batch 550 Loss 1.1125 Accuracy 0.6439


wandb: WARNING Step must only increase in log calls.  Step 4 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.1126454>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.64385843>}.


Epoch 4 Loss 1.1126 Accuracy 0.6439
Time taken for 1 epoch: 111.63783049583435 secs

epoch lasted: 111.64284253120422
Epoch 5 Batch 0 Loss 1.1026 Accuracy 0.6490
Epoch 5 Batch 50 Loss 1.0971 Accuracy 0.6477
Epoch 5 Batch 100 Loss 1.0959 Accuracy 0.6477
Epoch 5 Batch 150 Loss 1.0980 Accuracy 0.6476
Epoch 5 Batch 200 Loss 1.1013 Accuracy 0.6473
Epoch 5 Batch 250 Loss 1.0999 Accuracy 0.6477
Epoch 5 Batch 300 Loss 1.0991 Accuracy 0.6475
Epoch 5 Batch 350 Loss 1.0987 Accuracy 0.6476
Epoch 5 Batch 400 Loss 1.0983 Accuracy 0.6477
discarded batch 432
Epoch 5 Batch 450 Loss 1.0982 Accuracy 0.6478
Epoch 5 Batch 500 Loss 1.0978 Accuracy 0.6480
Epoch 5 Batch 550 Loss 1.0970 Accuracy 0.6483


wandb: WARNING Step must only increase in log calls.  Step 5 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.0964011>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.64854217>}.


Saving checkpoint for epoch 5 at ./checkpoints/train/ckpt-3
Epoch 5 Loss 1.0964 Accuracy 0.6485
Time taken for 1 epoch: 111.96454548835754 secs

epoch lasted: 111.96961283683777
Epoch 6 Batch 0 Loss 1.1154 Accuracy 0.6428
Epoch 6 Batch 50 Loss 1.0853 Accuracy 0.6516
Epoch 6 Batch 100 Loss 1.0863 Accuracy 0.6512
Epoch 6 Batch 150 Loss 1.0851 Accuracy 0.6515
Epoch 6 Batch 200 Loss 1.0855 Accuracy 0.6512
Epoch 6 Batch 250 Loss 1.0858 Accuracy 0.6511
discarded batch 272
Epoch 6 Batch 300 Loss 1.0846 Accuracy 0.6518
Epoch 6 Batch 350 Loss 1.0828 Accuracy 0.6523
Epoch 6 Batch 400 Loss 1.0825 Accuracy 0.6525
Epoch 6 Batch 450 Loss 1.0823 Accuracy 0.6525
Epoch 6 Batch 500 Loss 1.0815 Accuracy 0.6526
Epoch 6 Batch 550 Loss 1.0810 Accuracy 0.6529


wandb: WARNING Step must only increase in log calls.  Step 6 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.0808775>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.65295935>}.


Epoch 6 Loss 1.0809 Accuracy 0.6530
Time taken for 1 epoch: 111.8375313282013 secs



wandb: WARNING Step must only increase in log calls.  Step 6 < 11; dropping {'val_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.0153863>, 'val_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6700685>}.


discarded batch 5
Epoch 6 VALIDATION: Loss 1.0154 Accuracy 0.6701

epoch lasted: 112.23281669616699
Epoch 7 Batch 0 Loss 1.0827 Accuracy 0.6584
discarded batch 4
Epoch 7 Batch 50 Loss 1.0657 Accuracy 0.6575
Epoch 7 Batch 100 Loss 1.0667 Accuracy 0.6575
Epoch 7 Batch 150 Loss 1.0660 Accuracy 0.6573
Epoch 7 Batch 200 Loss 1.0682 Accuracy 0.6569
Epoch 7 Batch 250 Loss 1.0690 Accuracy 0.6564
Epoch 7 Batch 300 Loss 1.0687 Accuracy 0.6565
Epoch 7 Batch 350 Loss 1.0680 Accuracy 0.6566
Epoch 7 Batch 400 Loss 1.0680 Accuracy 0.6565
Epoch 7 Batch 450 Loss 1.0676 Accuracy 0.6565
Epoch 7 Batch 500 Loss 1.0675 Accuracy 0.6568
Epoch 7 Batch 550 Loss 1.0672 Accuracy 0.6567


wandb: WARNING Step must only increase in log calls.  Step 7 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.066862>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.656779>}.


Epoch 7 Loss 1.0669 Accuracy 0.6568
Time taken for 1 epoch: 111.77613687515259 secs

epoch lasted: 111.78118109703064
Epoch 8 Batch 0 Loss 1.1010 Accuracy 0.6571
Epoch 8 Batch 50 Loss 1.0622 Accuracy 0.6565
Epoch 8 Batch 100 Loss 1.0587 Accuracy 0.6587
Epoch 8 Batch 150 Loss 1.0585 Accuracy 0.6589
Epoch 8 Batch 200 Loss 1.0579 Accuracy 0.6589
Epoch 8 Batch 250 Loss 1.0568 Accuracy 0.6595
Epoch 8 Batch 300 Loss 1.0560 Accuracy 0.6596
Epoch 8 Batch 350 Loss 1.0548 Accuracy 0.6601
Epoch 8 Batch 400 Loss 1.0551 Accuracy 0.6602
Epoch 8 Batch 450 Loss 1.0551 Accuracy 0.6602
Epoch 8 Batch 500 Loss 1.0541 Accuracy 0.6605
discarded batch 538
Epoch 8 Batch 550 Loss 1.0533 Accuracy 0.6606


wandb: WARNING Step must only increase in log calls.  Step 8 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.0529895>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6607502>}.


Epoch 8 Loss 1.0530 Accuracy 0.6608
Time taken for 1 epoch: 111.82388281822205 secs

epoch lasted: 111.82938694953918
Epoch 9 Batch 0 Loss 1.0313 Accuracy 0.6658
Epoch 9 Batch 50 Loss 1.0428 Accuracy 0.6616
Epoch 9 Batch 100 Loss 1.0456 Accuracy 0.6628
Epoch 9 Batch 150 Loss 1.0434 Accuracy 0.6635
discarded batch 171
Epoch 9 Batch 200 Loss 1.0415 Accuracy 0.6641
Epoch 9 Batch 250 Loss 1.0425 Accuracy 0.6636
Epoch 9 Batch 300 Loss 1.0421 Accuracy 0.6636
Epoch 9 Batch 350 Loss 1.0411 Accuracy 0.6637
Epoch 9 Batch 400 Loss 1.0409 Accuracy 0.6639
Epoch 9 Batch 450 Loss 1.0401 Accuracy 0.6641
Epoch 9 Batch 500 Loss 1.0403 Accuracy 0.6639
Epoch 9 Batch 550 Loss 1.0392 Accuracy 0.6642


wandb: WARNING Step must only increase in log calls.  Step 9 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.0394306>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6642001>}.


Epoch 9 Loss 1.0394 Accuracy 0.6642
Time taken for 1 epoch: 111.70857906341553 secs

epoch lasted: 111.71388053894043
Epoch 10 Batch 0 Loss 1.0183 Accuracy 0.6770
Epoch 10 Batch 50 Loss 1.0348 Accuracy 0.6654
Epoch 10 Batch 100 Loss 1.0360 Accuracy 0.6654
Epoch 10 Batch 150 Loss 1.0354 Accuracy 0.6659
Epoch 10 Batch 200 Loss 1.0340 Accuracy 0.6663
Epoch 10 Batch 250 Loss 1.0313 Accuracy 0.6670
Epoch 10 Batch 300 Loss 1.0301 Accuracy 0.6674
Epoch 10 Batch 350 Loss 1.0293 Accuracy 0.6678
Epoch 10 Batch 400 Loss 1.0293 Accuracy 0.6677
Epoch 10 Batch 450 Loss 1.0282 Accuracy 0.6681
Epoch 10 Batch 500 Loss 1.0280 Accuracy 0.6681
Epoch 10 Batch 550 Loss 1.0275 Accuracy 0.6683
discarded batch 564


wandb: WARNING Step must only increase in log calls.  Step 10 < 11; dropping {'train_loss': <tf.Tensor: shape=(), dtype=float32, numpy=1.0277117>, 'train_accuracy': <tf.Tensor: shape=(), dtype=float32, numpy=0.6681584>}.


Saving checkpoint for epoch 10 at ./checkpoints/train/ckpt-4
Epoch 10 Loss 1.0277 Accuracy 0.6682
Time taken for 1 epoch: 112.03682971000671 secs

epoch lasted: 112.04185843467712


In [13]:
#@title Parameter persistence

transformer.save_weights("./optimus_rhyme")
#transformer.load_weights("./optimus_rhyme")


#emb_enc_w = transformer.encoder.embedding.get_weights()[0]
emb_enc_w = transformer.decoder.embedding.get_weights()[0]
print(emb_enc_w.shape)

out_v = open('vecs.tsv', 'w', encoding='utf-8')
out_m = open('meta.tsv', 'w', encoding='utf-8')

for num, word in enumerate(poetry_sy_lm_dataset.vocabulary.dictionary):
  vec = emb_enc_w[num] # skip 0, it's padding.
  out_m.write(word + "\n")
  out_v.write('\t'.join([str(x) for x in vec]) + "\n")
out_v.close()
out_m.close()


'''
%load_ext tensorboard
%tensorboard --logdir .
'''

(1900, 128)


'\n%load_ext tensorboard\n%tensorboard --logdir .\n'

# Tests

In [14]:
generate(1, k = 3, t = 0.9)

params: k=3, t=0.9
nel qual non si dee creder che s’ invii
per creatura l’ occhio tanto chiaro
e io ch’ al fine di tutt’ i disii
                                                                                         
 che per condo di come che la mannto
che sen che l’ una soltro suarena
pore l’ anco al con che per condena
                                                                                              
 se per la sore sor dal suo estra suo
e con che per che se se sontro seglio
ser sento a costa se per san conde
                                                                                         
 che la manto e la suo altro senta
ch’ essse chi sera che la son sorte
e sarrate suo come com’ a sua sua
                                                                                               
 e sante sente sera e san suo suo segno
che sante che la suondo e la monta
ché sonde la per la soltra carte
                                                                     

In [ ]:
#k=3
generate(1, k = 3, t = 1)

In [ ]:
#k=5
generate(1, k = 5, t = 1)